[2024-11-18T16:26:51.427+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-18T16:26:51.449+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Ciril_group.create-db manual__2024-11-18T16:26:50.691860+00:00 [queued]>
[2024-11-18T16:26:51.459+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Ciril_group.create-db manual__2024-11-18T16:26:50.691860+00:00 [queued]>
[2024-11-18T16:26:51.459+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 6
[2024-11-18T16:26:51.478+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): create-db> on 2024-11-18 16:26:50.691860+00:00
[2024-11-18T16:26:51.491+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=203) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-18T16:26:51.490+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'Ciril_group', 'create-db', 'manual__2024-11-18T16:26:50.691860+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/ciril_group_dag.py', '--cfg-path', '/tmp/tmp0t1um6pt']
[2024-11-18T16:26:51.492+0000] {standard_task_runner.py:72} INFO - Started process 214 to run task
[2024-11-18T16:26:51.493+0000] {standard_task_runner.py:105} INFO - Job 5: Subtask create-db
[2024-11-18T16:26:51.538+0000] {task_command.py:467} INFO - Running <TaskInstance: Ciril_group.create-db manual__2024-11-18T16:26:50.691860+00:00 [running]> on host 061dbc9e53b1
[2024-11-18T16:26:51.615+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Simo' AIRFLOW_CTX_DAG_ID='Ciril_group' AIRFLOW_CTX_TASK_ID='create-db' AIRFLOW_CTX_EXECUTION_DATE='2024-11-18T16:26:50.691860+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-18T16:26:50.691860+00:00'
[2024-11-18T16:26:51.616+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-18T16:26:51.650+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-18T16:26:51.652+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/opt/***/create-ciril-db.sh']
[2024-11-18T16:26:51.662+0000] {subprocess.py:86} INFO - Output:
[2024-11-18T16:26:51.863+0000] {subprocess.py:93} INFO - mysql: [Warning] Using a password on the command line interface can be insecure.
[2024-11-18T16:26:51.973+0000] {subprocess.py:93} INFO - ERROR 1050 (42S01) at line 11: Table 'people' already exists
[2024-11-18T16:26:51.986+0000] {subprocess.py:93} INFO - Error executing SQL script.
[2024-11-18T16:26:51.987+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-11-18T16:26:52.019+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-18T16:26:52.020+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=Ciril_group, task_id=create-db, run_id=manual__2024-11-18T16:26:50.691860+00:00, execution_date=20241118T162650, start_date=20241118T162651, end_date=20241118T162652
[2024-11-18T16:26:52.070+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-18T16:26:52.084+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-18T16:26:52.086+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
